# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mlx_tensor_pb2 as mlx__tensor__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mlx_tensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MLXTensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTensor = channel.unary_unary(
                '/mlxtensor.MLXTensorService/SendTensor',
                request_serializer=mlx__tensor__pb2.Tensor.SerializeToString,
                response_deserializer=mlx__tensor__pb2.TensorResponse.FromString,
                _registered_method=True)
        self.ResetCache = channel.unary_unary(
                '/mlxtensor.MLXTensorService/ResetCache',
                request_serializer=mlx__tensor__pb2.ResetCacheRequest.SerializeToString,
                response_deserializer=mlx__tensor__pb2.ResetCacheResponse.FromString,
                _registered_method=True)


class MLXTensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLXTensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTensor,
                    request_deserializer=mlx__tensor__pb2.Tensor.FromString,
                    response_serializer=mlx__tensor__pb2.TensorResponse.SerializeToString,
            ),
            'ResetCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetCache,
                    request_deserializer=mlx__tensor__pb2.ResetCacheRequest.FromString,
                    response_serializer=mlx__tensor__pb2.ResetCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlxtensor.MLXTensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlxtensor.MLXTensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLXTensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlxtensor.MLXTensorService/SendTensor',
            mlx__tensor__pb2.Tensor.SerializeToString,
            mlx__tensor__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlxtensor.MLXTensorService/ResetCache',
            mlx__tensor__pb2.ResetCacheRequest.SerializeToString,
            mlx__tensor__pb2.ResetCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
